apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-backend

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: orders-backend

  template:
    metadata:
      labels:
        app: orders-backend

    spec:
      containers:
        - name: orders-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}