apiVersion: v1
kind: Service
metadata:
  name: orders-backend-service

spec:
  selector:
    app: orders-backend

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

  type: {{ .Values.service.type }}